// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/darksford123x/app/ent/device"
	"github.com/darksford123x/app/ent/repairinvoice"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Device is the model entity for the Device schema.
type Device struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DeviceID holds the value of the "Device_ID" field.
	DeviceID int `json:"Device_ID,omitempty"`
	// CustomerID holds the value of the "Customer_ID" field.
	CustomerID int `json:"Customer_ID,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeviceQuery when eager-loading is set.
	Edges DeviceEdges `json:"edges"`
}

// DeviceEdges holds the relations/edges for other nodes in the graph.
type DeviceEdges struct {
	// Devices holds the value of the devices edge.
	Devices *RepairInvoice
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DevicesOrErr returns the Devices value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeviceEdges) DevicesOrErr() (*RepairInvoice, error) {
	if e.loadedTypes[0] {
		if e.Devices == nil {
			// The edge devices was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: repairinvoice.Label}
		}
		return e.Devices, nil
	}
	return nil, &NotLoadedError{edge: "devices"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Device) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
		&sql.NullInt64{}, // Device_ID
		&sql.NullInt64{}, // Customer_ID
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Device fields.
func (d *Device) assignValues(values ...interface{}) error {
	if m, n := len(values), len(device.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	d.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Device_ID", values[0])
	} else if value.Valid {
		d.DeviceID = int(value.Int64)
	}
	if value, ok := values[1].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Customer_ID", values[1])
	} else if value.Valid {
		d.CustomerID = int(value.Int64)
	}
	return nil
}

// QueryDevices queries the devices edge of the Device.
func (d *Device) QueryDevices() *RepairInvoiceQuery {
	return (&DeviceClient{config: d.config}).QueryDevices(d)
}

// Update returns a builder for updating this Device.
// Note that, you need to call Device.Unwrap() before calling this method, if this Device
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Device) Update() *DeviceUpdateOne {
	return (&DeviceClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (d *Device) Unwrap() *Device {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Device is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Device) String() string {
	var builder strings.Builder
	builder.WriteString("Device(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", Device_ID=")
	builder.WriteString(fmt.Sprintf("%v", d.DeviceID))
	builder.WriteString(", Customer_ID=")
	builder.WriteString(fmt.Sprintf("%v", d.CustomerID))
	builder.WriteByte(')')
	return builder.String()
}

// Devices is a parsable slice of Device.
type Devices []*Device

func (d Devices) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
