// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/darksford123x/app/ent/device"
	"github.com/darksford123x/app/ent/repairinvoice"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// DeviceCreate is the builder for creating a Device entity.
type DeviceCreate struct {
	config
	mutation *DeviceMutation
	hooks    []Hook
}

// SetDeviceID sets the Device_ID field.
func (dc *DeviceCreate) SetDeviceID(i int) *DeviceCreate {
	dc.mutation.SetDeviceID(i)
	return dc
}

// SetCustomerID sets the Customer_ID field.
func (dc *DeviceCreate) SetCustomerID(i int) *DeviceCreate {
	dc.mutation.SetCustomerID(i)
	return dc
}

// SetDevicesID sets the devices edge to RepairInvoice by id.
func (dc *DeviceCreate) SetDevicesID(id int) *DeviceCreate {
	dc.mutation.SetDevicesID(id)
	return dc
}

// SetNillableDevicesID sets the devices edge to RepairInvoice by id if the given value is not nil.
func (dc *DeviceCreate) SetNillableDevicesID(id *int) *DeviceCreate {
	if id != nil {
		dc = dc.SetDevicesID(*id)
	}
	return dc
}

// SetDevices sets the devices edge to RepairInvoice.
func (dc *DeviceCreate) SetDevices(r *RepairInvoice) *DeviceCreate {
	return dc.SetDevicesID(r.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (dc *DeviceCreate) Mutation() *DeviceMutation {
	return dc.mutation
}

// Save creates the Device in the database.
func (dc *DeviceCreate) Save(ctx context.Context) (*Device, error) {
	if _, ok := dc.mutation.DeviceID(); !ok {
		return nil, &ValidationError{Name: "Device_ID", err: errors.New("ent: missing required field \"Device_ID\"")}
	}
	if _, ok := dc.mutation.CustomerID(); !ok {
		return nil, &ValidationError{Name: "Customer_ID", err: errors.New("ent: missing required field \"Customer_ID\"")}
	}
	var (
		err  error
		node *Device
	)
	if len(dc.hooks) == 0 {
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DeviceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dc.mutation = mutation
			node, err = dc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			mut = dc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DeviceCreate) SaveX(ctx context.Context) *Device {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dc *DeviceCreate) sqlSave(ctx context.Context) (*Device, error) {
	d, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	d.ID = int(id)
	return d, nil
}

func (dc *DeviceCreate) createSpec() (*Device, *sqlgraph.CreateSpec) {
	var (
		d     = &Device{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: device.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: device.FieldID,
			},
		}
	)
	if value, ok := dc.mutation.DeviceID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: device.FieldDeviceID,
		})
		d.DeviceID = value
	}
	if value, ok := dc.mutation.CustomerID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: device.FieldCustomerID,
		})
		d.CustomerID = value
	}
	if nodes := dc.mutation.DevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   device.DevicesTable,
			Columns: []string{device.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repairinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return d, _spec
}
