// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/darksford123x/app/ent/repairinvoice"
	"github.com/darksford123x/app/ent/status"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// StatusCreate is the builder for creating a Status entity.
type StatusCreate struct {
	config
	mutation *StatusMutation
	hooks    []Hook
}

// SetStatusID sets the Status_ID field.
func (sc *StatusCreate) SetStatusID(i int) *StatusCreate {
	sc.mutation.SetStatusID(i)
	return sc
}

// SetStatusName sets the Status_name field.
func (sc *StatusCreate) SetStatusName(s string) *StatusCreate {
	sc.mutation.SetStatusName(s)
	return sc
}

// AddStatusInvoiceIDs adds the statusInvoice edge to RepairInvoice by ids.
func (sc *StatusCreate) AddStatusInvoiceIDs(ids ...int) *StatusCreate {
	sc.mutation.AddStatusInvoiceIDs(ids...)
	return sc
}

// AddStatusInvoice adds the statusInvoice edges to RepairInvoice.
func (sc *StatusCreate) AddStatusInvoice(r ...*RepairInvoice) *StatusCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sc.AddStatusInvoiceIDs(ids...)
}

// Mutation returns the StatusMutation object of the builder.
func (sc *StatusCreate) Mutation() *StatusMutation {
	return sc.mutation
}

// Save creates the Status in the database.
func (sc *StatusCreate) Save(ctx context.Context) (*Status, error) {
	if _, ok := sc.mutation.StatusID(); !ok {
		return nil, &ValidationError{Name: "Status_ID", err: errors.New("ent: missing required field \"Status_ID\"")}
	}
	if _, ok := sc.mutation.StatusName(); !ok {
		return nil, &ValidationError{Name: "Status_name", err: errors.New("ent: missing required field \"Status_name\"")}
	}
	if v, ok := sc.mutation.StatusName(); ok {
		if err := status.StatusNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Status_name", err: fmt.Errorf("ent: validator failed for field \"Status_name\": %w", err)}
		}
	}
	var (
		err  error
		node *Status
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StatusCreate) SaveX(ctx context.Context) *Status {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *StatusCreate) sqlSave(ctx context.Context) (*Status, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *StatusCreate) createSpec() (*Status, *sqlgraph.CreateSpec) {
	var (
		s     = &Status{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: status.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: status.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.StatusID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: status.FieldStatusID,
		})
		s.StatusID = value
	}
	if value, ok := sc.mutation.StatusName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: status.FieldStatusName,
		})
		s.StatusName = value
	}
	if nodes := sc.mutation.StatusInvoiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   status.StatusInvoiceTable,
			Columns: status.StatusInvoicePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repairinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return s, _spec
}
