// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/darksford123x/app/ent/status"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Status is the model entity for the Status schema.
type Status struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// StatusID holds the value of the "Status_ID" field.
	StatusID int `json:"Status_ID,omitempty"`
	// StatusName holds the value of the "Status_name" field.
	StatusName string `json:"Status_name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StatusQuery when eager-loading is set.
	Edges StatusEdges `json:"edges"`
}

// StatusEdges holds the relations/edges for other nodes in the graph.
type StatusEdges struct {
	// StatusInvoice holds the value of the statusInvoice edge.
	StatusInvoice []*RepairInvoice
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// StatusInvoiceOrErr returns the StatusInvoice value or an error if the edge
// was not loaded in eager-loading.
func (e StatusEdges) StatusInvoiceOrErr() ([]*RepairInvoice, error) {
	if e.loadedTypes[0] {
		return e.StatusInvoice, nil
	}
	return nil, &NotLoadedError{edge: "statusInvoice"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Status) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullInt64{},  // Status_ID
		&sql.NullString{}, // Status_name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Status fields.
func (s *Status) assignValues(values ...interface{}) error {
	if m, n := len(values), len(status.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Status_ID", values[0])
	} else if value.Valid {
		s.StatusID = int(value.Int64)
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Status_name", values[1])
	} else if value.Valid {
		s.StatusName = value.String
	}
	return nil
}

// QueryStatusInvoice queries the statusInvoice edge of the Status.
func (s *Status) QueryStatusInvoice() *RepairInvoiceQuery {
	return (&StatusClient{config: s.config}).QueryStatusInvoice(s)
}

// Update returns a builder for updating this Status.
// Note that, you need to call Status.Unwrap() before calling this method, if this Status
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Status) Update() *StatusUpdateOne {
	return (&StatusClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Status) Unwrap() *Status {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Status is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Status) String() string {
	var builder strings.Builder
	builder.WriteString("Status(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", Status_ID=")
	builder.WriteString(fmt.Sprintf("%v", s.StatusID))
	builder.WriteString(", Status_name=")
	builder.WriteString(s.StatusName)
	builder.WriteByte(')')
	return builder.String()
}

// StatusSlice is a parsable slice of Status.
type StatusSlice []*Status

func (s StatusSlice) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
