// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/darksford123x/app/ent/predicate"
	"github.com/darksford123x/app/ent/repairinvoice"
	"github.com/darksford123x/app/ent/status"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// StatusUpdate is the builder for updating Status entities.
type StatusUpdate struct {
	config
	hooks      []Hook
	mutation   *StatusMutation
	predicates []predicate.Status
}

// Where adds a new predicate for the builder.
func (su *StatusUpdate) Where(ps ...predicate.Status) *StatusUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetStatusID sets the Status_ID field.
func (su *StatusUpdate) SetStatusID(i int) *StatusUpdate {
	su.mutation.ResetStatusID()
	su.mutation.SetStatusID(i)
	return su
}

// AddStatusID adds i to Status_ID.
func (su *StatusUpdate) AddStatusID(i int) *StatusUpdate {
	su.mutation.AddStatusID(i)
	return su
}

// SetStatusName sets the Status_name field.
func (su *StatusUpdate) SetStatusName(s string) *StatusUpdate {
	su.mutation.SetStatusName(s)
	return su
}

// AddStatusInvoiceIDs adds the statusInvoice edge to RepairInvoice by ids.
func (su *StatusUpdate) AddStatusInvoiceIDs(ids ...int) *StatusUpdate {
	su.mutation.AddStatusInvoiceIDs(ids...)
	return su
}

// AddStatusInvoice adds the statusInvoice edges to RepairInvoice.
func (su *StatusUpdate) AddStatusInvoice(r ...*RepairInvoice) *StatusUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.AddStatusInvoiceIDs(ids...)
}

// Mutation returns the StatusMutation object of the builder.
func (su *StatusUpdate) Mutation() *StatusMutation {
	return su.mutation
}

// RemoveStatusInvoiceIDs removes the statusInvoice edge to RepairInvoice by ids.
func (su *StatusUpdate) RemoveStatusInvoiceIDs(ids ...int) *StatusUpdate {
	su.mutation.RemoveStatusInvoiceIDs(ids...)
	return su
}

// RemoveStatusInvoice removes statusInvoice edges to RepairInvoice.
func (su *StatusUpdate) RemoveStatusInvoice(r ...*RepairInvoice) *StatusUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.RemoveStatusInvoiceIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *StatusUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := su.mutation.StatusName(); ok {
		if err := status.StatusNameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Status_name", err: fmt.Errorf("ent: validator failed for field \"Status_name\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *StatusUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StatusUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StatusUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *StatusUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   status.Table,
			Columns: status.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: status.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.StatusID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: status.FieldStatusID,
		})
	}
	if value, ok := su.mutation.AddedStatusID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: status.FieldStatusID,
		})
	}
	if value, ok := su.mutation.StatusName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: status.FieldStatusName,
		})
	}
	if nodes := su.mutation.RemovedStatusInvoiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   status.StatusInvoiceTable,
			Columns: status.StatusInvoicePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repairinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.StatusInvoiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   status.StatusInvoiceTable,
			Columns: status.StatusInvoicePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repairinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{status.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// StatusUpdateOne is the builder for updating a single Status entity.
type StatusUpdateOne struct {
	config
	hooks    []Hook
	mutation *StatusMutation
}

// SetStatusID sets the Status_ID field.
func (suo *StatusUpdateOne) SetStatusID(i int) *StatusUpdateOne {
	suo.mutation.ResetStatusID()
	suo.mutation.SetStatusID(i)
	return suo
}

// AddStatusID adds i to Status_ID.
func (suo *StatusUpdateOne) AddStatusID(i int) *StatusUpdateOne {
	suo.mutation.AddStatusID(i)
	return suo
}

// SetStatusName sets the Status_name field.
func (suo *StatusUpdateOne) SetStatusName(s string) *StatusUpdateOne {
	suo.mutation.SetStatusName(s)
	return suo
}

// AddStatusInvoiceIDs adds the statusInvoice edge to RepairInvoice by ids.
func (suo *StatusUpdateOne) AddStatusInvoiceIDs(ids ...int) *StatusUpdateOne {
	suo.mutation.AddStatusInvoiceIDs(ids...)
	return suo
}

// AddStatusInvoice adds the statusInvoice edges to RepairInvoice.
func (suo *StatusUpdateOne) AddStatusInvoice(r ...*RepairInvoice) *StatusUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.AddStatusInvoiceIDs(ids...)
}

// Mutation returns the StatusMutation object of the builder.
func (suo *StatusUpdateOne) Mutation() *StatusMutation {
	return suo.mutation
}

// RemoveStatusInvoiceIDs removes the statusInvoice edge to RepairInvoice by ids.
func (suo *StatusUpdateOne) RemoveStatusInvoiceIDs(ids ...int) *StatusUpdateOne {
	suo.mutation.RemoveStatusInvoiceIDs(ids...)
	return suo
}

// RemoveStatusInvoice removes statusInvoice edges to RepairInvoice.
func (suo *StatusUpdateOne) RemoveStatusInvoice(r ...*RepairInvoice) *StatusUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.RemoveStatusInvoiceIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (suo *StatusUpdateOne) Save(ctx context.Context) (*Status, error) {
	if v, ok := suo.mutation.StatusName(); ok {
		if err := status.StatusNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Status_name", err: fmt.Errorf("ent: validator failed for field \"Status_name\": %w", err)}
		}
	}

	var (
		err  error
		node *Status
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StatusUpdateOne) SaveX(ctx context.Context) *Status {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *StatusUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StatusUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *StatusUpdateOne) sqlSave(ctx context.Context) (s *Status, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   status.Table,
			Columns: status.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: status.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Status.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.StatusID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: status.FieldStatusID,
		})
	}
	if value, ok := suo.mutation.AddedStatusID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: status.FieldStatusID,
		})
	}
	if value, ok := suo.mutation.StatusName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: status.FieldStatusName,
		})
	}
	if nodes := suo.mutation.RemovedStatusInvoiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   status.StatusInvoiceTable,
			Columns: status.StatusInvoicePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repairinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.StatusInvoiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   status.StatusInvoiceTable,
			Columns: status.StatusInvoicePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repairinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Status{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{status.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
