// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/darksford123x/app/ent/symptom"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Symptom is the model entity for the Symptom schema.
type Symptom struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SymptomID holds the value of the "Symptom_ID" field.
	SymptomID int `json:"Symptom_ID,omitempty"`
	// SymptomName holds the value of the "Symptom_name" field.
	SymptomName string `json:"Symptom_name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SymptomQuery when eager-loading is set.
	Edges SymptomEdges `json:"edges"`
}

// SymptomEdges holds the relations/edges for other nodes in the graph.
type SymptomEdges struct {
	// Symptoms holds the value of the symptoms edge.
	Symptoms []*RepairInvoice
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SymptomsOrErr returns the Symptoms value or an error if the edge
// was not loaded in eager-loading.
func (e SymptomEdges) SymptomsOrErr() ([]*RepairInvoice, error) {
	if e.loadedTypes[0] {
		return e.Symptoms, nil
	}
	return nil, &NotLoadedError{edge: "symptoms"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Symptom) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullInt64{},  // Symptom_ID
		&sql.NullString{}, // Symptom_name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Symptom fields.
func (s *Symptom) assignValues(values ...interface{}) error {
	if m, n := len(values), len(symptom.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Symptom_ID", values[0])
	} else if value.Valid {
		s.SymptomID = int(value.Int64)
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Symptom_name", values[1])
	} else if value.Valid {
		s.SymptomName = value.String
	}
	return nil
}

// QuerySymptoms queries the symptoms edge of the Symptom.
func (s *Symptom) QuerySymptoms() *RepairInvoiceQuery {
	return (&SymptomClient{config: s.config}).QuerySymptoms(s)
}

// Update returns a builder for updating this Symptom.
// Note that, you need to call Symptom.Unwrap() before calling this method, if this Symptom
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Symptom) Update() *SymptomUpdateOne {
	return (&SymptomClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Symptom) Unwrap() *Symptom {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Symptom is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Symptom) String() string {
	var builder strings.Builder
	builder.WriteString("Symptom(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", Symptom_ID=")
	builder.WriteString(fmt.Sprintf("%v", s.SymptomID))
	builder.WriteString(", Symptom_name=")
	builder.WriteString(s.SymptomName)
	builder.WriteByte(')')
	return builder.String()
}

// Symptoms is a parsable slice of Symptom.
type Symptoms []*Symptom

func (s Symptoms) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
