// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/darksford123x/app/ent/repairinvoice"
	"github.com/darksford123x/app/ent/symptom"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// SymptomCreate is the builder for creating a Symptom entity.
type SymptomCreate struct {
	config
	mutation *SymptomMutation
	hooks    []Hook
}

// SetSymptomID sets the Symptom_ID field.
func (sc *SymptomCreate) SetSymptomID(i int) *SymptomCreate {
	sc.mutation.SetSymptomID(i)
	return sc
}

// SetSymptomName sets the Symptom_name field.
func (sc *SymptomCreate) SetSymptomName(s string) *SymptomCreate {
	sc.mutation.SetSymptomName(s)
	return sc
}

// AddSymptomIDs adds the symptoms edge to RepairInvoice by ids.
func (sc *SymptomCreate) AddSymptomIDs(ids ...int) *SymptomCreate {
	sc.mutation.AddSymptomIDs(ids...)
	return sc
}

// AddSymptoms adds the symptoms edges to RepairInvoice.
func (sc *SymptomCreate) AddSymptoms(r ...*RepairInvoice) *SymptomCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sc.AddSymptomIDs(ids...)
}

// Mutation returns the SymptomMutation object of the builder.
func (sc *SymptomCreate) Mutation() *SymptomMutation {
	return sc.mutation
}

// Save creates the Symptom in the database.
func (sc *SymptomCreate) Save(ctx context.Context) (*Symptom, error) {
	if _, ok := sc.mutation.SymptomID(); !ok {
		return nil, &ValidationError{Name: "Symptom_ID", err: errors.New("ent: missing required field \"Symptom_ID\"")}
	}
	if _, ok := sc.mutation.SymptomName(); !ok {
		return nil, &ValidationError{Name: "Symptom_name", err: errors.New("ent: missing required field \"Symptom_name\"")}
	}
	if v, ok := sc.mutation.SymptomName(); ok {
		if err := symptom.SymptomNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Symptom_name", err: fmt.Errorf("ent: validator failed for field \"Symptom_name\": %w", err)}
		}
	}
	var (
		err  error
		node *Symptom
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SymptomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SymptomCreate) SaveX(ctx context.Context) *Symptom {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *SymptomCreate) sqlSave(ctx context.Context) (*Symptom, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *SymptomCreate) createSpec() (*Symptom, *sqlgraph.CreateSpec) {
	var (
		s     = &Symptom{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: symptom.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: symptom.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.SymptomID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: symptom.FieldSymptomID,
		})
		s.SymptomID = value
	}
	if value, ok := sc.mutation.SymptomName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: symptom.FieldSymptomName,
		})
		s.SymptomName = value
	}
	if nodes := sc.mutation.SymptomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   symptom.SymptomsTable,
			Columns: symptom.SymptomsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repairinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return s, _spec
}
