// Code generated by entc, DO NOT EDIT.

package device

const (
	// Label holds the string label denoting the device type in the database.
	Label = "device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldCustomerID holds the string denoting the customer_id field in the database.
	FieldCustomerID = "customer_id"

	// EdgeDevices holds the string denoting the devices edge name in mutations.
	EdgeDevices = "devices"

	// Table holds the table name of the device in the database.
	Table = "devices"
	// DevicesTable is the table the holds the devices relation/edge.
	DevicesTable = "repair_invoices"
	// DevicesInverseTable is the table name for the RepairInvoice entity.
	// It exists in this package in order to avoid circular dependency with the "repairinvoice" package.
	DevicesInverseTable = "repair_invoices"
	// DevicesColumn is the table column denoting the devices relation/edge.
	DevicesColumn = "device_devices"
)

// Columns holds all SQL columns for device fields.
var Columns = []string{
	FieldID,
	FieldDeviceID,
	FieldCustomerID,
}
