// Code generated by entc, DO NOT EDIT.

package status

const (
	// Label holds the string label denoting the status type in the database.
	Label = "status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatusID holds the string denoting the status_id field in the database.
	FieldStatusID = "status_id"
	// FieldStatusName holds the string denoting the status_name field in the database.
	FieldStatusName = "status_name"

	// EdgeStatusInvoice holds the string denoting the statusinvoice edge name in mutations.
	EdgeStatusInvoice = "statusInvoice"

	// Table holds the table name of the status in the database.
	Table = "status"
	// StatusInvoiceTable is the table the holds the statusInvoice relation/edge. The primary key declared below.
	StatusInvoiceTable = "status_statusInvoice"
	// StatusInvoiceInverseTable is the table name for the RepairInvoice entity.
	// It exists in this package in order to avoid circular dependency with the "repairinvoice" package.
	StatusInvoiceInverseTable = "repair_invoices"
)

// Columns holds all SQL columns for status fields.
var Columns = []string{
	FieldID,
	FieldStatusID,
	FieldStatusName,
}

var (
	// StatusInvoicePrimaryKey and StatusInvoiceColumn2 are the table columns denoting the
	// primary key for the statusInvoice relation (M2M).
	StatusInvoicePrimaryKey = []string{"status_id", "repair_invoice_id"}
)

var (
	// StatusNameValidator is a validator for the "Status_name" field. It is called by the builders before save.
	StatusNameValidator func(string) error
)
